name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch or the dev branch
  push:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: true
        type: choice
        options:
        - main
        - dev
        default: 'main'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment.
# Cancel any currently running job or workflow in the same concurrency group.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # When run manually, use the branch selected in the input.
          # When triggered by a push, use the branch that was pushed to.
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Create deployment artifact
        # This is a static site, so we just need to copy the files to a standard location.
        # The convention for GitHub Pages is to place static files in a `_site` directory.
        run: |
          mkdir -p _site
          cp index.html style.css script.js robots.txt test-image.png _site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the `_site` directory
          path: './_site'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4